server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass https://fpl-scout-production.up.railway.app;
        proxy_http_version 1.1;
        proxy_set_header Host fpl-scout-production.up.railway.app;
        proxy_ssl_server_name on;
    }

    location /ws {
        proxy_pass https://fpl-scout-production.up.railway.app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host fpl-scout-production.up.railway.app;
        proxy_ssl_server_name on;
    }
}